sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-wuhan-lr.aliyuncs.com
    bucket-name: codetao-cc
    access-key-id: LTAI5tL7bx2TqpJJV2JtxHwE
    access-key-secret: uhX0nwmeRDVUFRuiAtP7gA2G9QtCmN